"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { api, type MarketSession, type MarketAnalysis, type Candle } from "@/lib/api";

interface NarrativeBlock {
  role: string;
  narrative: string;
  word_count: number;
}

interface SessionEvent {
  timestamp: string;
  event_type: string;
  role: string;
  description: string;
  price: number | null;
  volume: number | null;
}

export default function SessionDetailPage() {
  const params = useParams();
  const sessionId = Number(params.sessionId);

  const [analysis, setAnalysis] = useState<MarketAnalysis | null>(null);
  const [candles, setCandles] = useState<Candle[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function load() {
      try {
        const [analysisData] = await Promise.allSettled([
          api.getAnalysis(sessionId),
        ]);

        if (analysisData.status === "fulfilled") {
          setAnalysis(analysisData.value);

          // Load candles for this asset
          if (analysisData.value.asset_id) {
            try {
              const c = await api.getCandles(analysisData.value.asset_id, { limit: 100 });
              setCandles(c);
            } catch { /* candles optional */ }
          }
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : String(err));
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [sessionId]);

  const blocks: NarrativeBlock[] = analysis?.narrative_blocks_json
    ? (Array.isArray(analysis.narrative_blocks_json) ? analysis.narrative_blocks_json : []) as NarrativeBlock[]
    : [];

  const events: SessionEvent[] = analysis?.key_moments_json
    ? (Array.isArray(analysis.key_moments_json) ? analysis.key_moments_json : []) as SessionEvent[]
    : [];

  return (
    <div>
      <h1 style={{ fontSize: "24px", marginBottom: "20px" }}>
        Session Detail — #{sessionId}
      </h1>

      {error && (
        <div style={{ padding: "12px", backgroundColor: "#fef2f2", color: "#b91c1c", borderRadius: "6px", marginBottom: "16px", fontSize: "13px" }}>
          {error}
        </div>
      )}
      {loading && <div style={{ color: "#999" }}>Loading...</div>}

      {analysis && (
        <>
          {/* Summary */}
          <div style={{ backgroundColor: "#fff", borderRadius: "8px", padding: "20px", marginBottom: "16px", boxShadow: "0 1px 3px rgba(0,0,0,0.1)" }}>
            <h2 style={{ fontSize: "16px", marginBottom: "12px", color: "#333" }}>Summary</h2>
            <p style={{ fontSize: "14px", color: "#555", lineHeight: "1.6" }}>
              {analysis.summary || "No summary available."}
            </p>
            <div style={{ display: "flex", gap: "16px", marginTop: "12px", fontSize: "12px", color: "#888" }}>
              <span>Date: {analysis.analysis_date}</span>
              <span>Generated by: {analysis.generated_by || "N/A"}</span>
              <span>Generated at: {analysis.generated_at ? new Date(analysis.generated_at).toLocaleString() : "N/A"}</span>
            </div>
          </div>

          {/* Narrative Blocks */}
          {blocks.length > 0 && (
            <div style={{ backgroundColor: "#fff", borderRadius: "8px", padding: "20px", marginBottom: "16px", boxShadow: "0 1px 3px rgba(0,0,0,0.1)" }}>
              <h2 style={{ fontSize: "16px", marginBottom: "12px", color: "#333" }}>Narrative Timeline</h2>
              {blocks.map((block, i) => (
                <div key={i} style={{ marginBottom: "16px", padding: "12px", backgroundColor: "#f8f9fa", borderRadius: "6px", borderLeft: `3px solid ${roleColor(block.role)}` }}>
                  <div style={{ fontSize: "11px", fontWeight: "bold", color: roleColor(block.role), marginBottom: "6px", textTransform: "uppercase" }}>
                    {block.role}
                  </div>
                  <p style={{ fontSize: "14px", color: "#444", lineHeight: "1.5", margin: 0 }}>
                    {block.narrative}
                  </p>
                  <div style={{ fontSize: "11px", color: "#999", marginTop: "4px" }}>
                    {block.word_count} words
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Key Events */}
          {events.length > 0 && (
            <div style={{ backgroundColor: "#fff", borderRadius: "8px", padding: "20px", marginBottom: "16px", boxShadow: "0 1px 3px rgba(0,0,0,0.1)" }}>
              <h2 style={{ fontSize: "16px", marginBottom: "12px", color: "#333" }}>Key Events</h2>
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "13px" }}>
                <thead>
                  <tr style={{ borderBottom: "2px solid #eee" }}>
                    <th style={{ textAlign: "left", padding: "8px", color: "#666" }}>Type</th>
                    <th style={{ textAlign: "left", padding: "8px", color: "#666" }}>Role</th>
                    <th style={{ textAlign: "left", padding: "8px", color: "#666" }}>Description</th>
                    <th style={{ textAlign: "right", padding: "8px", color: "#666" }}>Price</th>
                  </tr>
                </thead>
                <tbody>
                  {events.map((evt, i) => (
                    <tr key={i} style={{ borderBottom: "1px solid #f0f0f0" }}>
                      <td style={{ padding: "8px" }}>
                        <span style={{ padding: "2px 6px", backgroundColor: "#f0f0f0", borderRadius: "3px", fontSize: "11px" }}>
                          {evt.event_type}
                        </span>
                      </td>
                      <td style={{ padding: "8px", color: roleColor(evt.role), fontSize: "12px", fontWeight: "bold" }}>
                        {evt.role}
                      </td>
                      <td style={{ padding: "8px", color: "#555" }}>{evt.description}</td>
                      <td style={{ padding: "8px", textAlign: "right", fontFamily: "monospace" }}>
                        {evt.price != null ? `$${evt.price.toLocaleString()}` : "—"}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Candle Data */}
          {candles.length > 0 && (
            <div style={{ backgroundColor: "#fff", borderRadius: "8px", padding: "20px", boxShadow: "0 1px 3px rgba(0,0,0,0.1)" }}>
              <h2 style={{ fontSize: "16px", marginBottom: "12px", color: "#333" }}>
                Candle Data ({candles.length} candles)
              </h2>
              <div style={{ maxHeight: "300px", overflowY: "auto" }}>
                <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12px" }}>
                  <thead>
                    <tr style={{ borderBottom: "2px solid #eee", position: "sticky", top: 0, backgroundColor: "#fff" }}>
                      <th style={{ textAlign: "left", padding: "6px" }}>Time</th>
                      <th style={{ textAlign: "right", padding: "6px" }}>Open</th>
                      <th style={{ textAlign: "right", padding: "6px" }}>High</th>
                      <th style={{ textAlign: "right", padding: "6px" }}>Low</th>
                      <th style={{ textAlign: "right", padding: "6px" }}>Close</th>
                      <th style={{ textAlign: "right", padding: "6px" }}>Volume</th>
                    </tr>
                  </thead>
                  <tbody>
                    {candles.map((c) => (
                      <tr key={c.id} style={{ borderBottom: "1px solid #f5f5f5" }}>
                        <td style={{ padding: "6px", fontFamily: "monospace", fontSize: "11px" }}>
                          {new Date(c.timestamp).toLocaleTimeString()}
                        </td>
                        <td style={{ textAlign: "right", padding: "6px", fontFamily: "monospace" }}>{c.open.toFixed(2)}</td>
                        <td style={{ textAlign: "right", padding: "6px", fontFamily: "monospace" }}>{c.high.toFixed(2)}</td>
                        <td style={{ textAlign: "right", padding: "6px", fontFamily: "monospace" }}>{c.low.toFixed(2)}</td>
                        <td style={{ textAlign: "right", padding: "6px", fontFamily: "monospace", color: c.close >= c.open ? "#27ae60" : "#e74c3c" }}>
                          {c.close.toFixed(2)}
                        </td>
                        <td style={{ textAlign: "right", padding: "6px", fontFamily: "monospace" }}>
                          {c.volume.toLocaleString()}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}

function roleColor(role: string): string {
  switch (role) {
    case "SETUP": return "#3b82f6";
    case "CATALYST": return "#e94560";
    case "REACTION": return "#f39c12";
    case "DECISION_POINT": return "#8b5cf6";
    case "RESOLUTION": return "#27ae60";
    default: return "#666";
  }
}
